### ISSUE TITLE
Latest minor release breaks the build

### ISSUE THREAD

**Issue by bettiolo** [andyearnshaw/Intl.js#229]
Works with 1.2.4, breaks with 1.2.5:

```
Error: Cannot find module 'intl/locale-data/json/en-GB.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
[...]
```

**Comment by caridy** [comment]
dupe of https://github.com/andyearnshaw/Intl.js/issues/227

**Comment by bettiolo** [comment]
Ok, this is not going to be fixed.

**Comment by caridy** [comment]
@bettiolo I'm curious how are you using the json files? and why isn't a `jsons/` file enough?

**Comment by bettiolo** [comment]
@caridy I don't know, it must be some kind of third party library that has a dependency, I guess `react-intl` but I am not sure and I didn't have time to look into it. Sorry.

**Comment by caridy** [comment]
definitely not `react-intl` & co! must be something else.

**Comment by bettiolo** [comment]
Ok, it is our own's fault, we try to access the files directly:
```
Intl.__addLocaleData(require("intl/locale-data/json/en-GB.json"));
```

**Comment by caridy** [comment]
Just use the `require()` on the jsonp files, that should do the trick:

```
require("intl/locale-data/jsonp/en-GB.js"));
```
